http {
    resolver 1.1.1.1 ipv6=off;

    lua_shared_dict rate_limit_store 10m;
    lua_shared_dict rr_counter 1m;

    server {
        listen 80;

        location / {
            access_by_lua_file /etc/openresty/scripts/rate_limit.lua;
            content_by_lua_file /etc/openresty/scripts/shard.lua;
        }

        location = /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}
